name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Immunisation-Fhir-Api-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }} 
    short_service_name: ${{ variables.short_service_name }} 
    service_base_path: ${{ variables.service_base_path }} 
    apigee_deployments:
      - environment: internal-dev
        jinja_templates:
          DOMAIN_ENDPOINT: https://internal-dev.imms.dev.api.platform.nhs.uk
        post_deploy:
          - template: ./templates/post-deploy.yml
      - environment: internal-dev-sandbox
        proxy_path: sandbox
        jinja_templates:
          DOMAIN_ENDPOINT: just-dummy-value-for-successful-build
        post_deploy:
          - template: ./templates/post-deploy.yml
      - environment: sandbox
        proxy_path: sandbox
        jinja_templates:
          DOMAIN_ENDPOINT: just-dummy-value-for-successful-build
        depends_on:
          - internal_dev_sandbox
    # # Enable int environment when ready by uncommenting:
    #   - environment: int
    #     depends_on:
    #       - internal_dev
    #     post_deploy:
    #       - template: ./templates/post-deploy.yml
