variables:
  - group: status-endpoint
  - name: service_name
    value: immunisation-fhir-api
  - name: short_service_name
    value: ifa
  - name: service_base_path
    value: immunisation-fhir-api
  - name: pr_number
    value: ${{ split(variables['Build.SourceBranch'], '/')[2] }}
    
