FROM public.ecr.aws/lambda/python:3.9 as base

RUN pip install "poetry==1.5.*"

COPY poetry.lock pyproject.toml README.md ./
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --no-root --no-dev



# -----------------------------
FROM base as test

# install dev deps (runtime deps are already
# installed in the base image)
RUN poetry install

COPY src src
COPY tests tests

ENV DYNAMODB_TABLE_NAME=example_table
RUN python -m unittest

# -----------------------------
FROM base as runtime

COPY src .
RUN chmod 755 $(find .)
