"""Validation sets for each vaccine type"""

from models.mandation_functions import MandationRules


class ValidationSets:
    """
    Validation sets for each vaccine type.
    Each validation set identifies the mandation rule which applies for each field
    """

    def __init__(self) -> None:
        pass

    covid19 = {
        "occurrence_date_time": MandationRules.mandatory,
        "patient_identifier_value": MandationRules.required,
        "patient_name_given": MandationRules.mandatory,
        "patient_name_family": MandationRules.mandatory,
        "patient_birth_date": MandationRules.mandatory,
        "patient_gender": MandationRules.mandatory,
        "patient_address_postal_code": MandationRules.mandatory,
        "organization_identifier_value": MandationRules.mandatory,
        "organization_display": "optional",
        "identifier_value": MandationRules.mandatory,
        "identifier_system": MandationRules.mandatory,
        "practitioner_name_given": MandationRules.optional,
        "practitioner_name_family": "optional",
        "practitioner_identifier_value": MandationRules.required,
        "practitioner_identifier_system": MandationRules.mandatory_when_practitioner_identifier_value_present,
        "recorded": MandationRules.mandatory,
        "primary_source": MandationRules.mandatory,
        "report_origin_text": MandationRules.mandatory_when_primary_source_is_false,
        "vaccination_procedure_code": MandationRules.mandatory,
        "vaccination_procedure_display": MandationRules.required,
        "dose_number_positive_int": MandationRules.mandatory,
        "vaccine_code_coding_code": MandationRules.mandatory,
        "vaccine_code_coding_display": MandationRules.required,
        "manufacturer_display": MandationRules.mandatory,
        "lot_number": MandationRules.mandatory,
        "expiration_date": MandationRules.mandatory,
        "site_coding_code": MandationRules.required,
        "site_coding_display": MandationRules.required,
        "route_coding_code": MandationRules.mandatory,
        "route_coding_display": MandationRules.required,
        "dose_quantity_value": MandationRules.mandatory,
        "dose_quantity_code": MandationRules.mandatory,
        "dose_quantity_unit": MandationRules.required,
        "nhs_number_verification_status_code": MandationRules.mandatory,
        "nhs_number_verification_status_display": MandationRules.required,
        "organization_identifier_system": MandationRules.mandatory,
        "location_identifier_value": MandationRules.mandatory,
        "location_identifier_system": MandationRules.mandatory,
        "reason_code_coding_code": MandationRules.required,
        "reason_code_coding_display": MandationRules.required,
    }

    flu = {
        "occurrence_date_time": MandationRules.mandatory,
        "patient_identifier_value": MandationRules.required,
        "patient_name_given": MandationRules.mandatory,
        "patient_name_family": MandationRules.mandatory,
        "patient_birth_date": MandationRules.mandatory,
        "patient_gender": MandationRules.mandatory,
        "patient_address_postal_code": MandationRules.mandatory,
        "organization_identifier_value": MandationRules.mandatory,
        "organization_display": "optional",
        "identifier_value": MandationRules.mandatory,
        "identifier_system": MandationRules.mandatory,
        "practitioner_name_given": "optional",
        "practitioner_name_family": "optional",
        "practitioner_identifier_value": MandationRules.required,
        "practitioner_identifier_system": MandationRules.mandatory_when_practitioner_identifier_value_present,
        "recorded": MandationRules.mandatory,
        "primary_source": MandationRules.mandatory,
        "report_origin_text": MandationRules.mandatory_when_primary_source_is_false,
        "vaccination_procedure_code": MandationRules.mandatory,
        "vaccination_procedure_display": MandationRules.required,
        "dose_number_positive_int": MandationRules.mandatory,
        "vaccine_code_coding_code": MandationRules.mandatory,
        "vaccine_code_coding_display": MandationRules.required,
        "manufacturer_display": MandationRules.required,
        "lot_number": MandationRules.required,
        "expiration_date": MandationRules.required,
        "site_coding_code": MandationRules.required,
        "site_coding_display": MandationRules.required,
        "route_coding_code": MandationRules.mandatory,
        "route_coding_display": MandationRules.required,
        "dose_quantity_value": MandationRules.mandatory,
        "dose_quantity_code": MandationRules.mandatory,
        "dose_quantity_unit": MandationRules.required,
        "nhs_number_verification_status_code": MandationRules.mandatory,
        "nhs_number_verification_status_display": MandationRules.required,
        "organization_identifier_system": MandationRules.mandatory,
        "location_identifier_value": MandationRules.mandatory,
        "location_identifier_system": MandationRules.mandatory,
        "reason_code_coding_code": MandationRules.required,
        "reason_code_coding_display": MandationRules.required,
    }

    hpv = {
        "occurrence_date_time": MandationRules.mandatory,
        "patient_identifier_value": MandationRules.required,
        "patient_name_given": MandationRules.mandatory,
        "patient_name_family": MandationRules.mandatory,
        "patient_birth_date": MandationRules.mandatory,
        "patient_gender": MandationRules.mandatory,
        "patient_address_postal_code": MandationRules.mandatory,
        "organization_identifier_value": MandationRules.mandatory,
        "organization_display": "optional",
        "identifier_value": MandationRules.mandatory,
        "identifier_system": MandationRules.mandatory,
        "practitioner_name_given": "optional",
        "practitioner_name_family": "optional",
        "practitioner_identifier_value": MandationRules.required,
        "practitioner_identifier_system": "optional",
        "recorded": MandationRules.mandatory,
        "primary_source": MandationRules.mandatory,
        "report_origin_text": MandationRules.mandatory_when_primary_source_is_false,
        "vaccination_procedure_code": MandationRules.mandatory,
        "vaccination_procedure_display": MandationRules.required,
        "dose_number_positive_int": MandationRules.required,
        "vaccine_code_coding_code": MandationRules.mandatory,
        "vaccine_code_coding_display": MandationRules.required,
        "manufacturer_display": MandationRules.required,
        "lot_number": MandationRules.required,
        "expiration_date": MandationRules.required,
        "site_coding_code": MandationRules.required,
        "site_coding_display": MandationRules.required,
        "route_coding_code": MandationRules.required,
        "route_coding_display": MandationRules.required,
        "dose_quantity_value": MandationRules.required,
        "dose_quantity_code": MandationRules.required,
        "dose_quantity_unit": MandationRules.required,
        "nhs_number_verification_status_code": MandationRules.mandatory,
        "nhs_number_verification_status_display": MandationRules.required,
        "organization_identifier_system": MandationRules.mandatory,
        "location_identifier_value": MandationRules.mandatory,
        "location_identifier_system": MandationRules.mandatory,
        "reason_code_coding_code": MandationRules.required,
        "reason_code_coding_display": MandationRules.required,
    }

    mmr = {
        "occurrence_date_time": MandationRules.mandatory,
        "patient_identifier_value": MandationRules.required,
        "patient_name_given": MandationRules.mandatory,
        "patient_name_family": MandationRules.mandatory,
        "patient_birth_date": MandationRules.mandatory,
        "patient_gender": MandationRules.mandatory,
        "patient_address_postal_code": MandationRules.mandatory,
        "organization_identifier_value": MandationRules.mandatory,
        "organization_display": "optional",
        "identifier_value": MandationRules.mandatory,
        "identifier_system": MandationRules.mandatory,
        "practitioner_name_given": "optional",
        "practitioner_name_family": "optional",
        "practitioner_identifier_value": "optional",
        "practitioner_identifier_system": "optional",
        "recorded": MandationRules.mandatory,
        "primary_source": MandationRules.mandatory,
        "report_origin_text": MandationRules.mandatory_when_primary_source_is_false,
        "vaccination_procedure_code": MandationRules.mandatory,
        "vaccination_procedure_display": MandationRules.required,
        "dose_number_positive_int": MandationRules.required,
        "vaccine_code_coding_code": MandationRules.mandatory,
        "vaccine_code_coding_display": MandationRules.required,
        "manufacturer_display": MandationRules.required,
        "lot_number": MandationRules.required,
        "expiration_date": MandationRules.required,
        "site_coding_code": MandationRules.required,
        "site_coding_display": MandationRules.required,
        "route_coding_code": MandationRules.required,
        "route_coding_display": MandationRules.required,
        "dose_quantity_value": MandationRules.required,
        "dose_quantity_code": MandationRules.required,
        "dose_quantity_unit": MandationRules.required,
        "nhs_number_verification_status_code": MandationRules.mandatory,
        "nhs_number_verification_status_display": MandationRules.required,
        "organization_identifier_system": MandationRules.mandatory,
        "location_identifier_value": MandationRules.mandatory,  # TODO: Check as this was previously N/A
        "location_identifier_system": MandationRules.mandatory,  # TODO: Check as this was previously N/A
        "reason_code_coding_code": MandationRules.required,
        "reason_code_coding_display": MandationRules.required,
    }
