"""Validation sets for each vaccine type"""

from models.mandation_functions import MandationFunctions


class ValidationSets:
    """
    Validation sets for each vaccine type.
    Each validation set identifies the mandation rule which applies for each field
    """

    def __init__(self) -> None:
        pass

    covid19 = {
        "occurrence_date_time": MandationFunctions.mandatory,
        "patient_identifier_value": MandationFunctions.required,
        "patient_name_given": MandationFunctions.mandatory,
        "patient_name_family": MandationFunctions.mandatory,
        "patient_birth_date": MandationFunctions.mandatory,
        "patient_gender": MandationFunctions.mandatory,
        "patient_address_postal_code": MandationFunctions.mandatory,
        "organization_identifier_value": MandationFunctions.mandatory,
        "organization_display": MandationFunctions.optional,
        "identifier_value": MandationFunctions.mandatory,
        "identifier_system": MandationFunctions.mandatory,
        "practitioner_name_given": MandationFunctions.optional,
        "practitioner_name_family": MandationFunctions.optional,
        "practitioner_identifier_value": MandationFunctions.required,
        "practitioner_identifier_system": MandationFunctions.mandatory_when_practitioner_identifier_value_present,
        "recorded": MandationFunctions.mandatory,
        "primary_source": MandationFunctions.mandatory,
        "report_origin_text": MandationFunctions.mandatory_when_primary_source_is_false,
        "vaccination_procedure_code": MandationFunctions.mandatory,
        "vaccination_procedure_display": MandationFunctions.required,
        "dose_number_positive_int": MandationFunctions.mandatory,
        "vaccine_code_coding_code": MandationFunctions.mandatory,
        "vaccine_code_coding_display": MandationFunctions.required,
        "manufacturer_display": MandationFunctions.mandatory,
        "lot_number": MandationFunctions.mandatory,
        "expiration_date": MandationFunctions.mandatory,
        "site_coding_code": MandationFunctions.required,
        "site_coding_display": MandationFunctions.required,
        "route_coding_code": MandationFunctions.mandatory,
        "route_coding_display": MandationFunctions.required,
        "dose_quantity_value": MandationFunctions.mandatory,
        "dose_quantity_code": MandationFunctions.mandatory,
        "dose_quantity_unit": MandationFunctions.required,
        "nhs_number_verification_status_code": MandationFunctions.mandatory,
        "nhs_number_verification_status_display": MandationFunctions.required,
        "organization_identifier_system": MandationFunctions.mandatory,
        "location_identifier_value": MandationFunctions.mandatory,
        "location_identifier_system": MandationFunctions.mandatory,
        "reason_code_coding_code": MandationFunctions.required,
        "reason_code_coding_display": MandationFunctions.required,
    }

    flu = {
        "occurrence_date_time": MandationFunctions.mandatory,
        "patient_identifier_value": MandationFunctions.required,
        "patient_name_given": MandationFunctions.mandatory,
        "patient_name_family": MandationFunctions.mandatory,
        "patient_birth_date": MandationFunctions.mandatory,
        "patient_gender": MandationFunctions.mandatory,
        "patient_address_postal_code": MandationFunctions.mandatory,
        "organization_identifier_value": MandationFunctions.mandatory,
        "organization_display": MandationFunctions.optional,
        "identifier_value": MandationFunctions.mandatory,
        "identifier_system": MandationFunctions.mandatory,
        "practitioner_name_given": MandationFunctions.optional,
        "practitioner_name_family": MandationFunctions.optional,
        "practitioner_identifier_value": MandationFunctions.required,
        "practitioner_identifier_system": MandationFunctions.mandatory_when_practitioner_identifier_value_present,
        "recorded": MandationFunctions.mandatory,
        "primary_source": MandationFunctions.mandatory,
        "report_origin_text": MandationFunctions.mandatory_when_primary_source_is_false,
        "vaccination_procedure_code": MandationFunctions.mandatory,
        "vaccination_procedure_display": MandationFunctions.required,
        "dose_number_positive_int": MandationFunctions.mandatory,
        "vaccine_code_coding_code": MandationFunctions.mandatory,
        "vaccine_code_coding_display": MandationFunctions.required,
        "manufacturer_display": MandationFunctions.required,
        "lot_number": MandationFunctions.required,
        "expiration_date": MandationFunctions.required,
        "site_coding_code": MandationFunctions.required,
        "site_coding_display": MandationFunctions.required,
        "route_coding_code": MandationFunctions.mandatory,
        "route_coding_display": MandationFunctions.required,
        "dose_quantity_value": MandationFunctions.mandatory,
        "dose_quantity_code": MandationFunctions.mandatory,
        "dose_quantity_unit": MandationFunctions.required,
        "nhs_number_verification_status_code": MandationFunctions.mandatory,
        "nhs_number_verification_status_display": MandationFunctions.required,
        "organization_identifier_system": MandationFunctions.mandatory,
        "location_identifier_value": MandationFunctions.mandatory,
        "location_identifier_system": MandationFunctions.mandatory,
        "reason_code_coding_code": MandationFunctions.required,
        "reason_code_coding_display": MandationFunctions.required,
    }

    hpv = {
        "occurrence_date_time": MandationFunctions.mandatory,
        "patient_identifier_value": MandationFunctions.required,
        "patient_name_given": MandationFunctions.mandatory,
        "patient_name_family": MandationFunctions.mandatory,
        "patient_birth_date": MandationFunctions.mandatory,
        "patient_gender": MandationFunctions.mandatory,
        "patient_address_postal_code": MandationFunctions.mandatory,
        "organization_identifier_value": MandationFunctions.mandatory,
        "organization_display": MandationFunctions.optional,
        "identifier_value": MandationFunctions.mandatory,
        "identifier_system": MandationFunctions.mandatory,
        "practitioner_name_given": MandationFunctions.optional,
        "practitioner_name_family": MandationFunctions.optional,
        "practitioner_identifier_value": MandationFunctions.required,
        "practitioner_identifier_system": MandationFunctions.optional,
        "recorded": MandationFunctions.mandatory,
        "primary_source": MandationFunctions.mandatory,
        "report_origin_text": MandationFunctions.mandatory_when_primary_source_is_false,
        "vaccination_procedure_code": MandationFunctions.mandatory,
        "vaccination_procedure_display": MandationFunctions.required,
        "dose_number_positive_int": MandationFunctions.required,
        "vaccine_code_coding_code": MandationFunctions.mandatory,
        "vaccine_code_coding_display": MandationFunctions.required,
        "manufacturer_display": MandationFunctions.required,
        "lot_number": MandationFunctions.required,
        "expiration_date": MandationFunctions.required,
        "site_coding_code": MandationFunctions.required,
        "site_coding_display": MandationFunctions.required,
        "route_coding_code": MandationFunctions.required,
        "route_coding_display": MandationFunctions.required,
        "dose_quantity_value": MandationFunctions.required,
        "dose_quantity_code": MandationFunctions.required,
        "dose_quantity_unit": MandationFunctions.required,
        "nhs_number_verification_status_code": MandationFunctions.mandatory,
        "nhs_number_verification_status_display": MandationFunctions.required,
        "organization_identifier_system": MandationFunctions.mandatory,
        "location_identifier_value": MandationFunctions.mandatory,
        "location_identifier_system": MandationFunctions.mandatory,
        "reason_code_coding_code": MandationFunctions.required,
        "reason_code_coding_display": MandationFunctions.required,
    }

    mmr = {
        "occurrence_date_time": MandationFunctions.mandatory,
        "patient_identifier_value": MandationFunctions.required,
        "patient_name_given": MandationFunctions.mandatory,
        "patient_name_family": MandationFunctions.mandatory,
        "patient_birth_date": MandationFunctions.mandatory,
        "patient_gender": MandationFunctions.mandatory,
        "patient_address_postal_code": MandationFunctions.mandatory,
        "organization_identifier_value": MandationFunctions.mandatory,
        "organization_display": MandationFunctions.optional,
        "identifier_value": MandationFunctions.mandatory,
        "identifier_system": MandationFunctions.mandatory,
        "practitioner_name_given": MandationFunctions.optional,
        "practitioner_name_family": MandationFunctions.optional,
        "practitioner_identifier_value": MandationFunctions.optional,
        "practitioner_identifier_system": MandationFunctions.optional,
        "recorded": MandationFunctions.mandatory,
        "primary_source": MandationFunctions.mandatory,
        "report_origin_text": MandationFunctions.mandatory_when_primary_source_is_false,
        "vaccination_procedure_code": MandationFunctions.mandatory,
        "vaccination_procedure_display": MandationFunctions.required,
        "dose_number_positive_int": MandationFunctions.required,
        "vaccine_code_coding_code": MandationFunctions.mandatory,
        "vaccine_code_coding_display": MandationFunctions.required,
        "manufacturer_display": MandationFunctions.required,
        "lot_number": MandationFunctions.required,
        "expiration_date": MandationFunctions.required,
        "site_coding_code": MandationFunctions.required,
        "site_coding_display": MandationFunctions.required,
        "route_coding_code": MandationFunctions.required,
        "route_coding_display": MandationFunctions.required,
        "dose_quantity_value": MandationFunctions.required,
        "dose_quantity_code": MandationFunctions.required,
        "dose_quantity_unit": MandationFunctions.required,
        "nhs_number_verification_status_code": MandationFunctions.mandatory,
        "nhs_number_verification_status_display": MandationFunctions.required,
        "organization_identifier_system": MandationFunctions.mandatory,
        "location_identifier_value": MandationFunctions.mandatory,  # TODO: Check as this was previously N/A
        "location_identifier_system": MandationFunctions.mandatory,  # TODO: Check as this was previously N/A
        "reason_code_coding_code": MandationFunctions.required,
        "reason_code_coding_display": MandationFunctions.required,
    }
