from enum import Enum

""" 
    Enums for event names, operations, and action flags. 
    
    # case            eventName operation actionFlag
    ----------------- --------- --------- ----------
    create            INSERT    CREATE    NEW
    update            MODIFY    UPDATE    UPDATE
    logical delete    MODIFY    DELETE    DELETE
    physical delete   REMOVE    REMOVE    N/A
"""

class EventName():
    CREATE = "INSERT"
    UPDATE = "MODIFY"
    DELETE_LOGICAL = "MODIFY"
    DELETE_PHYSICAL = "REMOVE"

class Operation():
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE_LOGICAL = "DELETE"
    DELETE_PHYSICAL = "REMOVE"

class ActionFlag():
    CREATE = "NEW"
    UPDATE = "UPDATE"
    DELETE_LOGICAL = "DELETE"
    
class Gender(Enum):
    MALE = "1"
    FEMALE = "2"
    OTHER = "9"
    UNKNOWN = "0"
    
class ConversionFieldName(str, Enum):
    NHS_NUMBER = "NHS_NUMBER"
    PERSON_FORENAME = "PERSON_FORENAME"
    PERSON_SURNAME = "PERSON_SURNAME"
    PERSON_DOB = "PERSON_DOB"
    PERSON_GENDER_CODE = "PERSON_GENDER_CODE"
    PERSON_POSTCODE = "PERSON_POSTCODE"
    DATE_AND_TIME = "DATE_AND_TIME"
    SITE_CODE = "SITE_CODE"
    SITE_CODE_TYPE_URI = "SITE_CODE_TYPE_URI"
    UNIQUE_ID = "UNIQUE_ID"
    UNIQUE_ID_URI = "UNIQUE_ID_URI"
    ACTION_FLAG = "ACTION_FLAG"
    PERFORMING_PROFESSIONAL_FORENAME = "PERFORMING_PROFESSIONAL_FORENAME"
    PERFORMING_PROFESSIONAL_SURNAME = "PERFORMING_PROFESSIONAL_SURNAME"
    RECORDED_DATE = "RECORDED_DATE"
    PRIMARY_SOURCE = "PRIMARY_SOURCE"
    VACCINATION_PROCEDURE_CODE = "VACCINATION_PROCEDURE_CODE"
    VACCINATION_PROCEDURE_TERM = "VACCINATION_PROCEDURE_TERM"
    DOSE_SEQUENCE = "DOSE_SEQUENCE"
    VACCINE_PRODUCT_CODE = "VACCINE_PRODUCT_CODE"
    VACCINE_PRODUCT_TERM = "VACCINE_PRODUCT_TERM"
    VACCINE_MANUFACTURER = "VACCINE_MANUFACTURER"
    BATCH_NUMBER = "BATCH_NUMBER"
    EXPIRY_DATE = "EXPIRY_DATE"
    SITE_OF_VACCINATION_CODE = "SITE_OF_VACCINATION_CODE"
    SITE_OF_VACCINATION_TERM = "SITE_OF_VACCINATION_TERM"
    ROUTE_OF_VACCINATION_CODE = "ROUTE_OF_VACCINATION_CODE"
    ROUTE_OF_VACCINATION_TERM = "ROUTE_OF_VACCINATION_TERM"
    DOSE_AMOUNT = "DOSE_AMOUNT"
    DOSE_UNIT_CODE = "DOSE_UNIT_CODE"
    DOSE_UNIT_TERM = "DOSE_UNIT_TERM"
    INDICATION_CODE = "INDICATION_CODE"
    LOCATION_CODE = "LOCATION_CODE"
    LOCATION_CODE_TYPE_URI = "LOCATION_CODE_TYPE_URI"
