{
    "NHS_NUMBER": "9000000009",
    "PERSON_FORENAME": "Sarah",
    "PERSON_SURNAME": "Taylor",
    "PERSON_DOB": "19650228",
    "PERSON_GENDER_CODE": "0",
    "PERSON_POSTCODE": "EC1A 1BB",
    "DATE_AND_TIME": "20210207T132817",
    "SITE_CODE": "B0C4P",
    "SITE_CODE_TYPE_URI": "https://fhir.nhs.uk/Id/ods-organization-code",
    "ACTION_FLAG": "DELETE",
    "PERFORMING_PROFESSIONAL_FORENAME": "Florence",
    "PERFORMING_PROFESSIONAL_SURNAME": "Nightingale",
    "RECORDED_DATE": "20210207",
    "PRIMARY_SOURCE": "true",
    "VACCINATION_PROCEDURE_CODE": "1324681000000101",
    "VACCINATION_PROCEDURE_TERM": "Administration of first dose of severe acute respiratory syndrome coronavirus 2 vaccine (procedure)",
    "DOSE_SEQUENCE": 1,
    "VACCINE_PRODUCT_CODE": "39114911000001105",
    "VACCINE_PRODUCT_TERM": "COVID-19 Vaccine Vaxzevria (ChAdOx1 S [recombinant]) not less than 2.5x100,000,000 infectious units/0.5ml dose suspension for injection multidose vials (AstraZeneca UK Ltd) (product)",
    "VACCINE_MANUFACTURER": "AstraZeneca Ltd",
    "BATCH_NUMBER": "4120Z001",
    "EXPIRY_DATE": "20210702",
    "SITE_OF_VACCINATION_CODE": "368208006",
    "SITE_OF_VACCINATION_TERM": "Left upper arm structure (body structure)",
    "ROUTE_OF_VACCINATION_CODE": "78421000",
    "ROUTE_OF_VACCINATION_TERM": "Intramuscular route (qualifier value)",
    "DOSE_AMOUNT": "0.5",
    "DOSE_UNIT_CODE": "",
    "DOSE_UNIT_TERM": "milliliter",
    "INDICATION_CODE": "443684005",
    "LOCATION_CODE": "X99999",
    "LOCATION_CODE_TYPE_URI": "https://fhir.nhs.uk/Id/ods-organization-code",
}, {
    "NHS_NUMBER": "9000000009",
    "PERSON_FORENAME": "Sarah",
    "PERSON_SURNAME": "Taylor",
    "PERSON_DOB": "19650228",
    "PERSON_GENDER_CODE": "0",
    "PERSON_POSTCODE": "EC1A 1BB",
    "DATE_AND_TIME": "20210207T132817",
    "SITE_CODE": "B0C4P",
    "SITE_CODE_TYPE_URI": "https://fhir.nhs.uk/Id/ods-organization-code",
    "ACTION_FLAG": "DELETE",
    "PERFORMING_PROFESSIONAL_FORENAME": "Florence",
    "PERFORMING_PROFESSIONAL_SURNAME": "Nightingale",
    "RECORDED_DATE": "20210207",
    "PRIMARY_SOURCE": "true",
    "VACCINATION_PROCEDURE_CODE": "1324681000000101",
    "VACCINATION_PROCEDURE_TERM": "Administration of first dose of severe acute respiratory syndrome coronavirus 2 vaccine (procedure)",
    "DOSE_SEQUENCE": 1,
    "VACCINE_PRODUCT_CODE": "39114911000001105",
    "VACCINE_PRODUCT_TERM": "COVID-19 Vaccine Vaxzevria (ChAdOx1 S [recombinant]) not less than 2.5x100,000,000 infectious units/0.5ml dose suspension for injection multidose vials (AstraZeneca UK Ltd) (product)",
    "VACCINE_MANUFACTURER": "AstraZeneca Ltd",
    "BATCH_NUMBER": "4120Z001",
    "EXPIRY_DATE": "20210702",
    "SITE_OF_VACCINATION_CODE": "368208006",
    "SITE_OF_VACCINATION_TERM": "Left upper arm structure (body structure)",
    "ROUTE_OF_VACCINATION_CODE": "78421000",
    "ROUTE_OF_VACCINATION_TERM": "Intramuscular route (qualifier value)",
    "DOSE_AMOUNT": "0.5",
    "DOSE_UNIT_CODE": "",
    "DOSE_UNIT_TERM": "milliliter",
    "INDICATION_CODE": "443684005",
    "LOCATION_CODE": "X99999",
    "LOCATION_CODE_TYPE_URI": "https://fhir.nhs.uk/Id/ods-organization-code",
}, {
    "NHS_NUMBER": "9000000009",
    "PERSON_FORENAME": "Sarah",
    "PERSON_SURNAME": "Taylor",
    "PERSON_DOB": "19650228",
    "PERSON_GENDER_CODE": "0",
    "PERSON_POSTCODE": "EC1A 1BB",
    "DATE_AND_TIME": "20210207T132817",
    "SITE_CODE": "B0C4P",
    "SITE_CODE_TYPE_URI": "https://fhir.nhs.uk/Id/ods-organization-code",
    "ACTION_FLAG": "DELETE",
    "PERFORMING_PROFESSIONAL_FORENAME": "Florence",
    "PERFORMING_PROFESSIONAL_SURNAME": "Nightingale",
    "RECORDED_DATE": "20210207",
    "PRIMARY_SOURCE": "true",
    "VACCINATION_PROCEDURE_CODE": "1324681000000101",
    "VACCINATION_PROCEDURE_TERM": "Administration of first dose of severe acute respiratory syndrome coronavirus 2 vaccine (procedure)",
    "DOSE_SEQUENCE": 1,
    "VACCINE_PRODUCT_CODE": "39114911000001105",
    "VACCINE_PRODUCT_TERM": "COVID-19 Vaccine Vaxzevria (ChAdOx1 S [recombinant]) not less than 2.5x100,000,000 infectious units/0.5ml dose suspension for injection multidose vials (AstraZeneca UK Ltd) (product)",
    "VACCINE_MANUFACTURER": "AstraZeneca Ltd",
    "BATCH_NUMBER": "4120Z001",
    "EXPIRY_DATE": "20210702",
    "SITE_OF_VACCINATION_CODE": "368208006",
    "SITE_OF_VACCINATION_TERM": "Left upper arm structure (body structure)",
    "ROUTE_OF_VACCINATION_CODE": "78421000",
    "ROUTE_OF_VACCINATION_TERM": "Intramuscular route (qualifier value)",
    "DOSE_AMOUNT": "0.5",
    "DOSE_UNIT_CODE": "",
    "DOSE_UNIT_TERM": "milliliter",
    "INDICATION_CODE": "443684005",
    "LOCATION_CODE": "X99999",
    "LOCATION_CODE_TYPE_URI": "https://fhir.nhs.uk/Id/ods-organization-code",
}
